In [1]:
import cv2

def convert_grayscale_to_3channel(input_path, output_path):
    grayscale_image = cv2.imread(input_path, cv2.IMREAD_GRAYSCALE)
    duplicate_image = cv2.merge((grayscale_image,) * 3)
    cv2.imwrite(output_path, duplicate_image)

if __name__ == "__main__":
    input_image_path = "path_to_grayscale_image.png"
    output_image_path = "path_to_output_3channel_image.png"

    convert_grayscale_to_3channel(input_image_path, output_image_path)

In [2]:
import os
import cv2

def convert_grayscale_to_3channel(input_path, output_path):
    grayscale_image = cv2.imread(input_path, cv2.IMREAD_GRAYSCALE)
    duplicate_image = cv2.merge((grayscale_image,) * 3)
    cv2.imwrite(output_path, duplicate_image)

def batch_convert_images_in_folder(input_folder, output_folder):
    # Ensure the output folder exists
    os.makedirs(output_folder, exist_ok=True)

    # List all files in the input folder
    files = os.listdir(input_folder)

    for filename in files:
        input_path = os.path.join(input_folder, filename)
        output_path = os.path.join(output_folder, filename)

        # Check if the file is an image (you can add more extensions if needed)
        if filename.lower().endswith((".jpg", ".jpeg", ".png", ".gif", ".bmp")):
            convert_grayscale_to_3channel(input_path, output_path)

if __name__ == "__main__":
    input_folder = "C:\\Users\\mhajj\\Documents\\RUTILEA\\mhajjaj\\GearInspection-Dataset3\\CategoryNG\\ClassAll\\train\\images"
    output_folder = "C:\\Users\\mhajj\\Documents\\RUTILEA\\mhajjaj\\GearInspection-Dataset3\\CategoryNG\\ClassAll\\train\\images"

    batch_convert_images_in_folder(input_folder, output_folder)
    print("Image conversion completed.")


Image conversion completed.


In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import transforms
from torch.utils.data import DataLoader, random_split
from sklearn.metrics import confusion_matrix, classification_report
import numpy as np
from PIL import Image

In [2]:
import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import transforms
from torch.utils.data import DataLoader, random_split
from sklearn.metrics import confusion_matrix, classification_report
import numpy as np
from PIL import Image

# Define a simple CNN model
class SimpleCNN(nn.Module):
    def __init__(self, num_classes=8):
        super(SimpleCNN, self).__init__()
        self.conv1 = nn.Conv2d(3, 32, kernel_size=3, stride=1, padding=1)
        self.pool = nn.MaxPool2d(kernel_size=2, stride=2)
        self.fc1 = nn.Linear(32 * 460 * 700, 128)  # Adjusted input size for 920x1400
        self.fc2 = nn.Linear(128, num_classes)

    def forward(self, x):
        x = self.pool(nn.functional.relu(self.conv1(x)))
        x = x.view(x.size(0), -1)
        x = nn.functional.relu(self.fc1(x))
        x = self.fc2(x)
        return x

# Dummy dataset with random data (replace with your actual dataset)
# You need to adjust the dataset loading and preprocessing according to your data
class DummyDataset(torch.utils.data.Dataset):
    def __init__(self, num_samples, num_classes, image_size=(920, 1400), transform=None):
        self.data = torch.randn(num_samples, 3, *image_size)  # Random data, adjust to your dataset
        self.targets = torch.randint(0, num_classes, (num_samples,))
        self.transform = transform

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        sample, target = self.data[idx], self.targets[idx]
        if self.transform:
            sample = self.transform(sample)
        return sample, target

# Data preprocessing and data loaders (replace with your actual data)
transform = transforms.Compose([
    transforms.ToPILImage(),  # Convert tensor to PIL Image
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5])
])

dummy_dataset = DummyDataset(num_samples=800, num_classes=8, transform=transform)
train_size = int(0.8 * len(dummy_dataset))
test_size = len(dummy_dataset) - train_size
train_dataset, test_dataset = random_split(dummy_dataset, [train_size, test_size])

batch_size = 16
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

# Initialize the model and optimizer
model = SimpleCNN(num_classes=8)
optimizer = optim.Adam(model.parameters(), lr=0.001)
criterion = nn.CrossEntropyLoss()

# Training loop (you should replace this with your actual training loop)
num_epochs = 10

for epoch in range(num_epochs):
    model.train()
    for images, labels in train_loader:
        optimizer.zero_grad()
        outputs = model(images)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

# Evaluate the model on the test dataset
model.eval()
all_labels = []
all_predictions = []

with torch.no_grad():
    for images, labels in test_loader:
        outputs = model(images)
        _, predicted = torch.max(outputs, 1)
        all_labels.extend(labels.numpy())
        all_predictions.extend(predicted.numpy())

# Calculate the confusion matrix
confusion_mat = confusion_matrix(all_labels, all_predictions)

# Calculate class-wise metrics using classification_report
class_names = ['class0', 'class1', 'class2', 'class3', 'class4', 'class5', 'class6', 'class7']
class_metrics = classification_report(
    all_labels,
    all_predictions,
    target_names=class_names,
    output_dict=True
)

# Print or display the confusion matrix and class-wise metrics
print("Confusion Matrix:")
print(confusion_mat)
print("\nClass-wise Metrics:")
for class_name, metrics in class_metrics.items():
    if class_name in class_names:
        print(f"Class: {class_name}")
        print(f"Precision: {metrics['precision']:.2f}")
        print(f"Recall: {metrics['recall']:.2f}")
        print(f"F1-Score: {metrics['f1-score']:.2f}")
        print(f"Support: {metrics['support']}")


KeyboardInterrupt: 

In [2]:
import os
import torch.nn as nn
import torch.nn.functional as F

In [3]:
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        # Convolutional layers
        self.conv1 = nn.Conv2d(1, 32, kernel_size=3, stride=1, padding=1)
        self.conv2 = nn.Conv2d(32, 64, kernel_size=3, stride=1, padding=1)
        self.pool = nn.MaxPool2d(kernel_size=2, stride=2)
        
        # Fully connected layers
        self.fc1 = nn.Linear(64 * 256 * 320, 128)  
        self.fc2 = nn.Linear(128, 64)
        self.fc3 = nn.Linear(64, 1)  

    def forward(self, x):
        # Convolutional layers
        x = self.pool(nn.functional.relu(self.conv1(x)))
        x = self.pool(nn.functional.relu(self.conv2(x)))
        
        # Flatten the tensor for fully connected layers
        x = x.view(x.size(0), -1)
        
        # Fully connected layers
        x = nn.functional.relu(self.fc1(x))
        x = nn.functional.relu(self.fc2(x))
        x = self.fc3(x)
        return x

In [4]:
import torch

# Instantiate your neural network (assuming you've defined it as 'net')
net = Net()

# Create a sample input tensor with the same shape as your data
sample_input = torch.randn(8, 1, 512, 640)  # Replace with actual input size

# Pass the sample input through the network
output = net(sample_input)

# Print the shape of the output from the last convolutional/pooling layer
# In this example, we assume the last layer is self.conv2
last_layer_output_shape = net.conv2(output).shape
print("Output shape of the last convolutional/pooling layer:", last_layer_output_shape)


RuntimeError: mat1 and mat2 shapes cannot be multiplied (8x1310720 and 5242880x128)

In [9]:
import torch
import torch.nn as nn

class CustomNet(nn.Module):
    def __init__(self):
        super(CustomNet, self).__init__()
        # Convolutional layers
        self.conv1 = nn.Conv2d(1, 32, kernel_size=3, stride=1, padding=1)
        self.conv2 = nn.Conv2d(32, 64, kernel_size=3, stride=1, padding=1)
        self.pool = nn.MaxPool2d(kernel_size=2, stride=2)
        
        # Fully connected layers
        self.fc1 = nn.Linear(64 * 128 * 160, 128)  # Adjust the input size based on your needs
        self.fc2 = nn.Linear(128, 64)
        self.fc3 = nn.Linear(64, 1)  # Output size depends on your task

    def forward(self, x):
        # Convolutional layers
        x = self.pool(nn.functional.relu(self.conv1(x)))
        x = self.pool(nn.functional.relu(self.conv2(x)))

        # After the last pooling layer
        print("Shape after the last pooling layer:", x.shape)

        
        # Flatten the tensor for fully connected layers
        x = x.view(x.size(0), -1)
        
        # Fully connected layers
        x = nn.functional.relu(self.fc1(x))
        x = nn.functional.relu(self.fc2(x))
        x = self.fc3(x)
        return x

# Instantiate the custom neural network
net = CustomNet()

# Print the network architecture
print(net)

# Create a sample input tensor with the correct shape
sample_input = torch.randn(8, 1, 512, 640)

# Pass the sample input through the network
output = net(sample_input)

# Print the output shape to verify
print("Output shape:", output.shape)

# Check the number of channels
num_channels = sample_input.shape[1]
print("Number of channels in input data:", num_channels)


CustomNet(
  (conv1): Conv2d(1, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (conv2): Conv2d(32, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (pool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (fc1): Linear(in_features=1310720, out_features=128, bias=True)
  (fc2): Linear(in_features=128, out_features=64, bias=True)
  (fc3): Linear(in_features=64, out_features=1, bias=True)
)
Shape after the last pooling layer: torch.Size([8, 64, 128, 160])
Output shape: torch.Size([8, 1])
Number of channels in input data: 1


In [10]:
import torch
import numpy as np
from sklearn.metrics import confusion_matrix, classification_report

# Initialize an empty confusion matrix
num_classes = len(class_names)  # Replace with the number of classes in your dataset
confusion_matrix_total = np.zeros((num_classes, num_classes), dtype=int)

# Set your model to evaluation mode
model.eval()

# Iterate through the data loader
for inputs, labels in dataloader:
    # Make predictions using your model
    with torch.no_grad():
        outputs = model(inputs)
        _, predicted = torch.max(outputs, 1)

    # Convert tensors to numpy arrays
    predicted = predicted.cpu().numpy()
    labels = labels.cpu().numpy()

    # Update the confusion matrix
    confusion_matrix_total += confusion_matrix(labels, predicted, labels=range(num_classes))

# Calculate performance metrics for each class
class_metrics = classification_report(
    np.arange(num_classes),
    np.arange(num_classes),
    target_names=class_names,
    output_dict=True
)

# Print or save the confusion matrix and class-wise metrics
print("Confusion Matrix:")
print(confusion_matrix_total)

print("Class-wise Metrics:")
for class_name, metrics in class_metrics.items():
    if class_name in class_names:
        print(f"Class: {class_name}")
        print(f"Precision: {metrics['precision']:.2f}")
        print(f"Recall: {metrics['recall']:.2f}")
        print(f"F1-Score: {metrics['f1-score']:.2f}")
        print(f"Support: {metrics['support']}")


NameError: name 'class_names' is not defined

In [11]:
import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, transforms
from sklearn.metrics import confusion_matrix, classification_report
import numpy as np

# Define a simple CNN model
class SimpleCNN(nn.Module):
    def __init__(self, num_classes=10):
        super(SimpleCNN, self).__init__()
        self.conv1 = nn.Conv2d(3, 32, kernel_size=3, stride=1, padding=1)
        self.pool = nn.MaxPool2d(kernel_size=2, stride=2)
        self.fc1 = nn.Linear(32 * 16 * 16, 128)
        self.fc2 = nn.Linear(128, num_classes)

    def forward(self, x):
        x = self.pool(nn.functional.relu(self.conv1(x)))
        x = x.view(x.size(0), -1)
        x = nn.functional.relu(self.fc1(x))
        x = self.fc2(x)
        return x

# Dummy dataset with torchvision
transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))  # Normalize for example
])

train_dataset = datasets.CIFAR10(root='./data', train=True, download=True, transform=transform)
test_dataset = datasets.CIFAR10(root='./data', train=False, download=True, transform=transform)

batch_size = 64
train_loader = torch.utils.data.DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
test_loader = torch.utils.data.DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

# Initialize the model and optimizer
model = SimpleCNN(num_classes=10)
optimizer = optim.Adam(model.parameters(), lr=0.001)
criterion = nn.CrossEntropyLoss()


100%|██████████| 170498071/170498071 [00:34<00:00, 4904249.32it/s]


Extracting ./data\cifar-10-python.tar.gz to ./data
Files already downloaded and verified


In [12]:
# Training loop (assuming you've trained your model)

# Evaluate the model on the test dataset
model.eval()
all_labels = []
all_predictions = []

with torch.no_grad():
    for images, labels in test_loader:
        outputs = model(images)
        _, predicted = torch.max(outputs, 1)
        all_labels.extend(labels.numpy())
        all_predictions.extend(predicted.numpy())

# Calculate the confusion matrix
confusion_mat = confusion_matrix(all_labels, all_predictions)

# Calculate class-wise metrics using classification_report
class_names = ['airplane', 'automobile', 'bird', 'cat', 'deer', 'dog', 'frog', 'horse', 'ship', 'truck']
class_metrics = classification_report(
    all_labels,
    all_predictions,
    target_names=class_names,
    output_dict=True
)

# Print or display the confusion matrix and class-wise metrics
print("Confusion Matrix:")
print(confusion_mat)
print("\nClass-wise Metrics:")
for class_name, metrics in class_metrics.items():
    if class_name in class_names:
        print(f"Class: {class_name}")
        print(f"Precision: {metrics['precision']:.2f}")
        print(f"Recall: {metrics['recall']:.2f}")
        print(f"F1-Score: {metrics['f1-score']:.2f}")
        print(f"Support: {metrics['support']}")


Confusion Matrix:
[[  3   0   0   3   0 245   0 292 455   2]
 [  1   0   2   2   0 124   0 125 746   0]
 [  0   0   0   1   0 119   0 176 704   0]
 [  2   0   0   0   0 153   0  91 752   2]
 [  0   0   0   0   0  63   1  92 843   1]
 [  0   0   0   0   0 113   0 146 740   1]
 [  0   0   0   0   0  83   0  59 858   0]
 [  1   0   3   0   0 138   0  89 766   3]
 [  2   0   1   3   0 159   0 245 585   5]
 [  4   0   3   1   0 234   0  69 684   5]]

Class-wise Metrics:
Class: airplane
Precision: 0.23
Recall: 0.00
F1-Score: 0.01
Support: 1000.0
Class: automobile
Precision: 0.00
Recall: 0.00
F1-Score: 0.00
Support: 1000.0
Class: bird
Precision: 0.00
Recall: 0.00
F1-Score: 0.00
Support: 1000.0
Class: cat
Precision: 0.00
Recall: 0.00
F1-Score: 0.00
Support: 1000.0
Class: deer
Precision: 0.00
Recall: 0.00
F1-Score: 0.00
Support: 1000.0
Class: dog
Precision: 0.08
Recall: 0.11
F1-Score: 0.09
Support: 1000.0
Class: frog
Precision: 0.00
Recall: 0.00
F1-Score: 0.00
Support: 1000.0
Class: horse
Preci

c:\Users\mhajj\Documents\RUTILEA\rutilea\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\mhajj\Documents\RUTILEA\rutilea\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\mhajj\Documents\RUTILEA\rutilea\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [25]:
# import torch

# # Simulated predictions and targets (replace with actual data)
# predictions = torch.tensor([0, 1, 2, 0, 2, 1])
# targets = torch.tensor([0, 1, 2, 1, 2, 0])

# # Calculate the multiclass confusion matrix
# confusion_matrix = torch.zeros(3, 3)

# for t, p in zip(targets, predictions):
#     confusion_matrix[t, p] += 1

# # Print the confusion matrix
# print("Confusion Matrix:")
# print(confusion_matrix)

In [3]:
import os
import sys
from PIL import Image

from tensorboardX import SummaryWriter

import matplotlib.pyplot as plt
import numpy as np
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

import seaborn as sn
import pandas as pd

import torch
import torchvision
from torchvision import transforms
from torchvision.datasets import ImageFolder
from torchvision.io import read_image
from torch.utils.data import Dataset

import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

from super_gradients.training import Trainer, models
from super_gradients.training.dataloaders.dataloaders import (
    coco_detection_yolo_format_train, coco_detection_yolo_format_val
)
from super_gradients.training.losses import PPYoloELoss
from super_gradients.training.metrics import DetectionMetrics_050
from super_gradients.training.models.detection_models.pp_yolo_e import (
    PPYoloEPostPredictionCallback
)

sys.stdout = sys.__stdout__

In [4]:
class config:
    #trainer params
    HOME = os.getcwd()

    CHECKPOINT_DIR = f'{HOME}\checkpoint\AGI-Dataset' #specify the path you want to save checkpoints to
    EXPERIMENT_NAME = 'AGIExperiment' 

    ##dataset params
    DATA_DIR = f'{HOME}\GearInspection-Dataset3\CategoryNG\ClassAll' 
    LOGS = f'{CHECKPOINT_DIR}\AGILogs'

    # CATEGORY = 'CategoryNG\ClassAll'

    TRAIN_IMAGES_DIR = 'train\images' 
    TRAIN_LABELS_DIR = 'train\labels' 

    VAL_IMAGES_DIR = 'valid\images'
    VAL_LABELS_DIR = 'valid\labels' 

    TEST_IMAGES_DIR = 'test\images' 
    TEST_LABELS_DIR = 'test\labels'

    #what class names do you have
    CLASSES = ['akkon', 'dakon', 'kizu', 'hakkon', 'kuromoyou', 'mizunokori', 'senkizu', 'yogore']

    NUM_CLASSES = len(CLASSES)

    DATALOADER_PARAMS={
    'batch_size':64,
    'num_workers':2
    }

    EPOCHS = 1
    RUNNING_LOSS = 0.0
    ACCURACY = 0.0

    # model params
    MODEL_NAME = 'yolo_nas_l' # choose from yolo_nas_s, yolo_nas_m, yolo_nas_l
    PRETRAINED_WEIGHTS = 'coco' 

In [3]:
# Define a custom dataset class to load images and labels from separate folders
class CustomImageDataset(Dataset):
    def __init__(self, images_dir, labels_dir, transform=None):
        self.images_dir = images_dir
        self.labels_dir = labels_dir
        self.transform = transform
        self.image_filenames = os.listdir(images_dir)

    def __len__(self):
        return len(self.image_filenames)

    def __getitem__(self, idx):
        img_name = os.path.join(self.images_dir, self.image_filenames[idx])
        label_name = os.path.join(self.labels_dir, self.image_filenames[idx] + '.txt')  # Assuming labels are in text files

        print(label_name)

        image = read_image(img_name)
        
        # Load and process the label file (adjust as needed based on your label file format)
        with open(label_name, 'r') as label_file:
            label = label_file.read().strip()
            label = int(label)  # Assuming labels are integer values

        if self.transform:
            image = self.transform(image)

        return image, label

In [4]:
# Define your data transformation
transform = transforms.Compose(
    [transforms.ToTensor(),
    transforms.Normalize((0.5,), (0.5,))])

# Create custom datasets for train, validation, and test
train_dataset = CustomImageDataset(
    images_dir=f'{config.DATA_DIR}\\{config.TRAIN_IMAGES_DIR}',
    labels_dir=f'{config.DATA_DIR}\\{config.TRAIN_LABELS_DIR}',
    transform=transform
)

val_dataset = CustomImageDataset(
    images_dir=f'{config.DATA_DIR}\\{config.VAL_IMAGES_DIR}',
    labels_dir=f'{config.DATA_DIR}\\{config.VAL_LABELS_DIR}',
    transform=transform
)

test_dataset = CustomImageDataset(
    images_dir=f'{config.DATA_DIR}\\{config.TEST_IMAGES_DIR}',
    labels_dir=f'{config.DATA_DIR}\\{config.TEST_LABELS_DIR}',
    transform=transform
)

In [5]:
train_root = f'{config.DATA_DIR}\\{config.TRAIN_IMAGES_DIR}'

print("train_root")

In [8]:
# Create custom datasets for train, validation, and test
train_dataset = ImageFolder(
    root=train_root,
    transform=transform
)

val_dataset = ImageFolder(
    root=config.VAL_IMAGES_DIR,
    transform=transform
)

test_dataset = ImageFolder(
    root=config.TEST_IMAGES_DIR,
    transform=transform
)

FileNotFoundError: Couldn't find any class folder in c:\Users\mhajj\Documents\RUTILEA\mhajjaj\GearInspection-Dataset3\CategoryNG\ClassAll\train\images.